services:
  app:
    build:
      context: ./app
    container_name: todo-app
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - database
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`app.localhost`) || Host(`app.devops.gapi.me`)"
      - "traefik.http.routers.app.service=app"
      - "traefik.http.routers.app.tls.certResolver=letsencrypt"
      - "traefik.http.services.app.loadbalancer.server.port=8080"

  database:
    image: postgres:18.1
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql

  loki:
    image: grafana/loki:3.6.0
    container_name: loki
    user: "0"
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - ./configs/loki-config.yaml:/etc/loki/loki-config.yaml
      - loki_data:/usr/local/loki/data

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    command: run /etc/alloy/config.alloy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./configs/config.alloy:/etc/alloy/config.alloy

  grafana:
    image: grafana/grafana:12.2.1
    container_name: grafana
    volumes:
      - ./configs/grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.localhost`) || Host(`grafana.devops.gapi.me`)"
      - "traefik.http.routers.grafana.service=grafana"
      - "traefik.http.routers.grafana.tls.certResolver=letsencrypt"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

  traefik:
    image: traefik:v3.6
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  db_data:
  loki_data:
  grafana_data: